# Generated by Django 4.1 on 2022-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
