# Generated by Django 4.1 on 2022-09-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistorymodel",
            name="total_price",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
